Update working group description.
Joystream/handbook pull request #13
Opened 2020-10-15 15:30 UTC by shamil-gadelshin

Added extrinsics description:
- set budget
- leader spending
- set status text

2020-10-15 16:56 UTC, bedeho requested changes

2020-10-15 16:56 UTC, bedeho commented on governance/working-groups.md
> +### Setting the working group budget
The description level targeted in the handbook is functinal, not at the module level, hence I think we dont explain things at the abstraction level of public module methods or root origin gate extrinsics. Instead we would here explain this as a proposal in the proposal section of the handbook, could you do that?

2020-10-15 16:56 UTC, bedeho commented on governance/working-groups.md
> +### Setting the working group status text
Can you also add this as a concept in the concept section, and also mention this as one of the activities that fall within the domain of responsibility of the lead in the `Roles` section.

2020-10-16 11:29 UTC, shamil-gadelshin commented on governance/working-groups.md
> +### Setting the working group status text
Updated the Leader role description.

2020-10-16 11:47 UTC, shamil-gadelshin commented on governance/working-groups.md
> +### Setting the working group budget
I added the `Set Working Group Budget` description to the handbook (which is yet to be implemented).

2020-10-16 13:06 UTC, bedeho approved these changes

2020-10-16 13:06 UTC, merged