Council operations description
Joystream/handbook pull request #14
Opened 2020-10-25 23:10 UTC by ondratra

This PR adds description for the council operations.

2020-10-27 11:58 UTC, bedeho requested changes
- The operations should be written more as a reference, not as an explainer, so please remove all rationalisation there, and just explain pure conditions and checks.
- Remember to explain how signer is authenticated.
- Overall try to write at a low level of detail using the lowest level concepts already introduced in the article, rather than high level descriptions that are a bit more vauge.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* **Not enough winners** Not enough candidates received any votes, and a new council with enough members can't be established.
I thought we just made some deterministic, but arbitrary, choice of winners? Is this no longer the case? See right above in the same document

```
Importantly, even if there is an insufficient number of valid votes revealed to render a set of winners with non-zero backing stake, the runtime will just pick a winning set deterministically.
```

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +| council_user_id | Membership id uniquely identifying the user. |
This list cant be right, where is the staking account?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* In case the user has announced candidacy in one of the previous elections and hasn't released candidacy stake yet,
1. Only describe the checks neutrally, do not give explanations, this part of the documentation is not the plain to build understanding, only be a reference.
2. This check cannot be right? First, you are referencing an account not in the param list, but beyond this you are saying that this has to be the same account as the origin. Also there is nothing that explains what the signer authentication actually is, namely controller of memeber.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +| council_user_id | Membership id uniquely identifying the user. |
Lets call this member_id, its not really the council id, it may become that if the person wins.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* The user is candidating in the current election.
How is signer authenticated?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* Candidacy can be withdrawn only during the same Candidacy Announcement phase in which it has been announced.
Rephrase as a pure condition, not an explanation.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* A vote can be cast only during the Voting phase.
How is signer authenticated?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* A vote can be revealed only during the Revealing phase.
How is signer authenticated?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* A stake can be released only after the new council election ends.
How is signer authenticated?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* A candidacy stake is still locked. Note that successful candidates have their stake automatically converted
How is signer authenticated?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* Candidacy can be withdrawn only during the same Candidacy Announcement phase in which it has been announced.
This condition probably should go before the other one, as there are only candidates at all if one is in the announcement phase.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +| `stake` | Amount of currency user wants to stake for the vote. The stake must be at least `MINIUMUM_VOTING_STAKE`. The candidates with the most staked amount behind the votes recieved will win. |
Don't you need account?

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +  The commitment will be verified later in [Reveal vote](#user-content-reveal-vote).
Drop explanations.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +* One account can vote only once in the election. If you want to vote for multiple candidates, repeat vote with a different account(s).
Drop expanation.

2020-10-27 11:58 UTC, bedeho commented on governance/council.md
> +| `salt` | The (cryptographic) salt used to calculate the sealed commitment. Salt's lenght can't be higher than `MAX_SALT_LENGTH` |
Description should not have conditions in it, also dont explain what its used for, just what it is.

2020-10-30 08:30 UTC, ondratra commented
I rephrased conditions and parameters description. `account_id` parameter description was also added - it is always derived from the origin.

2020-10-30 08:32 UTC, ondratra commented on governance/council.md
> +| council_user_id | Membership id uniquely identifying the user. |
We definitely can, but the reason I have choosen `council_user_id` is that `member_id` sounds much more as councils elected member. Should we change it anyway?

2020-11-06 21:02 UTC, ondratra commented on governance/council.md
> +* **Not enough winners** Not enough candidates received any votes, and a new council with enough members can't be established.
After discussing this, we have decided to leave it as it is. The scenario is very unlikely because candidates can vote for themself. Also, since we are allowing an infinite number of candidates, the only deterministic way to elect members would be to elect the first announcing candidates.

2020-11-06 21:04 UTC, ondratra commented
Issues from the previous review have been addressed, and a description for adding a candidacy note was added.

2020-11-07 10:13 UTC, bedeho requested changes

2020-11-07 10:13 UTC, bedeho commented on governance/council.md
> +| `account_id` | Staking account. Derived from the Origin. |
There is no staking account supplied when setting a candidacy note?

`set_candidacy_note(origin, council_user_id: T::CouncilUserId, note: Vec<u8>) `

2020-11-23 13:10 UTC, ondratra commented on governance/council.md
> +| council_user_id | Membership id uniquely identifying the user. |
The variable is called `membership_id` now.

2020-11-23 13:12 UTC, ondratra commented on governance/council.md
> +| `account_id` | Staking account. Derived from the Origin. |
The association is made via `membership_id` (previously named `council_user_id`).

2020-12-01 19:20 UTC, merged